-- Agrégats journaliers pour accélérer les pages dashboard/flows/costs
CREATE TABLE IF NOT EXISTS daily_metrics (
  day DATE NOT NULL,
  n_tx BIGINT UNSIGNED NOT NULL DEFAULT 0,
  n_payment BIGINT UNSIGNED NOT NULL DEFAULT 0,
  n_topup BIGINT UNSIGNED NOT NULL DEFAULT 0,
  n_interest BIGINT UNSIGNED NOT NULL DEFAULT 0,
  n_unknown BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sum_in_raw DECIMAL(65,0) NOT NULL DEFAULT 0,
  sum_out_raw DECIMAL(65,0) NOT NULL DEFAULT 0,
  sum_payment_raw DECIMAL(65,0) NOT NULL DEFAULT 0,
  sum_topup_raw DECIMAL(65,0) NOT NULL DEFAULT 0,
  sum_interest_raw DECIMAL(65,0) NOT NULL DEFAULT 0,
  gas_eth DECIMAL(38,18) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (day)
) ENGINE=InnoDB;
